apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    team: finance
    version: 1.0.1
    environment: development
  annotations:
    description: Ini adalah deskripsi
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80